myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, ),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(),
         name='product_detail'),
    path('products/add/', views.ProductCreateView.as_view(), name="add_product"),
    path('products/update/<int:pk>/',
         views.ProductUpdateView.as_view(), name="update_product"),
    path('products/delete/<int:pk>/',
         views.ProductDelete.as_view(), name="delete_product"),
    path('products/mylistings', views.my_listings, name='mylistings'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.contrib.auth import views as authentication_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='createprofile'),
    path('sellerprofile/<int:id>', views.seller_profile, name='sellerprofile'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# this is a model model

# Create your models here
class Product(models.Model):

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myapp:products')

    seller_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pic')
    contact_number = models.CharField(max_length=100, default="99999999")

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    # defination of the form field
    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'class': 'focus:outline-none', 'placeholder': 'demo@gmail.com'}))
    username = forms.CharField(required=True,  widget=forms.TextInput(
        attrs={'class': 'focus:outline-none', 'placeholder': 'Jhon Doe'}))
    password1 = forms.CharField(required=True,  widget=forms.PasswordInput(
        attrs={'class': 'focus:outline-none', 'placeholder': '****************'}))
    password2 = forms.CharField(required=True,  widget=forms.PasswordInput(
        attrs={'class': 'focus:outline-none', 'placeholder': '****************'}))

    # the model to which the form belongs
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

myapp/views.py
from contextvars import Context
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.http import HttpResponse
from .models import Product
# Create your views here.


def index(request):
    return HttpResponse("Hello World")

# Class based view for above products view[listview]


class ProductListView(ListView):
    model = Product
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 3


def product_detail(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product
    }
    return render(request, 'myapp/detail.html', context)

# class based view for above product detail view [DetailView]


class ProductDetailView(DetailView):
    model = Product
    template_name = 'myapp/detail.html'
    context_object_name = 'product'


@login_required
def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        seller_name = request.user
        product = Product(name=name, price=price, desc=desc,
                          image=image, seller_name=seller_name)
        product.save()
    return render(request, 'myapp/addproduct.html')

# Class based view for creating a product


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'desc', 'image', 'seller_name']
    # product_form.html


def update_product(request, id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products')
    context = {
        'product': product
    }
    return render(request, 'myapp/updateproduct.html', context)


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'desc', 'image', 'seller_name']
    template_name_suffix = '_update_form'


def delete_product(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product,
    }
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/products')
    return render(request, 'myapp/delete.html', context)

# class based delete view


class ProductDelete(DeleteView):
    model = Product


def my_listings(request):
    products = Product.objects.filter(seller_name=request.user)
    context = {
        'products': products
    }
    return render(request, 'myapp/mylistings.html', context)

users/views.py
from django.shortcuts import render
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp/products')
    form = NewUserForm()
    context = {
        'form': form
    }
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    return render(request, 'users/profile.html')


def create_profile(request):
    if request.method == 'POST':
        contact_number = request.POST.get('contact_number')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user=user, image=image,
                          contact_number=contact_number)
        profile.save()
    return render(request, 'users/createprofile.html')


def seller_profile(request, id):
    seller = User.objects.get(id=id)
    context = {
        'seller': seller
    }
    return render(request, 'users/sellerprofile.html', context)

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">+ Add products</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype = 'multipart/form-data'>
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="iPhone" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="900" type="text" name="price" id="price">
        
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="this is an iPhone" type="text" name="desc" id="desc">
        
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product image</label>
        <input class="py-2 mr-10 text-gray-700" placeholder="Browse..." type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Add product"> 
    </div>
    
</form>

{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<html>
  <head>
    <title>Buy&sell</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}" />
  </head>
  <body>
    <nav class="bg-white shadow-lg">
      <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
          <div class="flex space-x-7">
            <div>
              <a href="" class="flex items-center px-2 py-4">
                <img
                  class="h-8 w-8"
                  src="{% static 'myapp/images/shopping bag.png' %}"
                  alt=""
                />
                <span class="text-gray-500 font-semibold text-lg"
                  >Buy&Sell</span
                >
              </a>
            </div>
            <div class="items-center flex space-x-1">
              <a
                href="{% url 'myapp:products' %}"
                class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500"
                >Home</a
              >
              <a href="{% url 'myapp:add_product' %}" class="py-4 px-2 text-gray-500 font-semibold">Post Ad</a>
              <a href="{% url 'myapp:products' %}" class="py-4 px-2 text-gray-500 font-semibold"
                >View Products</a
              >
              {% if user.is_authenticated %}
                <a class="py-4 px-20 text-red-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                <a class="py-4 px-20 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                <a class="py-4 px-20 text-gray-500 font-semibold" href="{% url 'myapp:mylistings' %}">My listings</a>
              {% else %}
                <a class="py-4 px-40 text-green-500 font-semibold" href="{% url 'users:login' %}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
  </body>
</html>

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">Delete products</h1>
<form method="POST" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">Are you sure you want to delete this product</label>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">{{product.name}}</label>
    </div>
    <div class="mb-4">
        <img src="{{product.image.url}}" alt="">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" name="confirm" value="confirm">
    <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:products' %}">Cancel</a>
</form>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="flex m-10 p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="w-2/3 m-5 text-xl">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-500" >$ {{product.price}}</div>
        <div class="mt-5 text-gray-500" >{{product.desc}}</div>
        <div class="mt-5  text-gray-500 text-bold">Posted by: <a class="text-red-500 font-bold" href="{% url 'users:sellerprofile' product.seller_name.id %}">{{product.seller_name}}</a></div>
        <div class="mt-5  text-gray-500 text-bold">Contact: {{product.seller_name.profile.contact_number}}</div>
    </div>
</div>

<button class="flex m-10 p-10"><a href="/myapp/products/">Back to home</a></button>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %} {% load static %} {% block content %}

<!--Site hero starts here-->
<main
  class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28"
>
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline">Premium products</span>
      <span class="block text-green-500 xl:inline">Non premium prices</span>
    </h1>
    <p
      class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0"
    >
      Get the best quality used product across the globe, Free shipping
    </p>
  </div>
</main>
<!--Site hero ends here-->

<div class="flex mt-5 p-10 justify-center">
  <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent products</h2>
</div>

<div class="mt-5 p-10 justify-center">
  <h2>Search Products</h2>
  <form method="GET">
    <input
      class="font-bold text-lg text-gray-700"
      name="product_name"
      id="product_name"
      placeholder="Type a product to search"
      type="text"
    />
  </form>
</div>

<div
  class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5"
>
  <!--Card 1-->
  {% for product in products %}
  <a
    href="{% url 'myapp:product_detail' product.id %}"
    class="text-primary text-decoration-none"
  >
    <div class="rounded overflow-hidden shadow-lg">
      <img class="w-full" src="{{product.image.url}}" alt="" />
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">{{product.name}}</div>
        <div class="font-bold text-xl text-green-500 mb-2">
          $ {{product.price}}
        </div>
        <div class="font-bold mb-2">
          Posted by:
          <span class="text-indigo-500">{{product.seller_name}} </span>
        </div>
        <p class="text-gray-700 text-base">{{product.desc}}</p>
      </div>
    </div>
  </a>
  {% endfor %}
</div>

<!--pagination code starts here-->
<div class="pagination flex justify-center items-center mb-20">
  <span>
    {% if page_obj.has_previous %}
    <a
      class="text-sm font-medium border py-2 px-2 items-center inline-flex relative text-green-500 border-green-500 z-10"
      href="?page=1"
      >First</a
    >
    <a
      class="text-sm font-medium border py-2 px-2 items-center inline-flex relative text-green-500 border-green-500 z-10"
      href="?page={{page_obj.previous_page_number}}"
      >Previous</a
    >
    {% endif %}
    <span
      class="text-sm font-medium border py-2 px-2 items-center inline-flex relative text-green-500 border-green-500 z-10"
    >
      page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next %}
    <a
      class="text-sm font-medium border py-2 px-2 items-center inline-flex relative text-green-500 border-green-500 z-10"
      href="?page={{page_obj.next_page_number}}"
      >Next</a
    >
    <a
      class="text-sm font-medium border py-2 px-2 items-center inline-flex relative text-green-500 border-green-500 z-10"
      href="?page={{page_obj.paginator.num_pages}}"
      >Last</a
    >
    {% endif %}
  </span>
</div>
<!--pagination code ends here-->

{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="text-2xl m-10 p-10 font-bold">My listings</div>
{% for product in products %}
<div class="itemcontainer flex shadow-lg m-10 p-10">
    <span class="w-1/5">
        <img class="w-40 h-40" src="{{product.image.url}}" alt="">
    </span>
    <span class="w-2/5 flex"> 
        <div class=" font-bold text-gray-700">{{product.name}}</div>
        <div class=" text-green-500">$ {{product.price}}</div>
        <div class=" ">{{product.desc}}</div>    
    </span>
    <span class="w-1/5 mx-10 my-10">
        <a class="bg-green-500 text-white font-bold px-5 py-2" href="{% url 'myapp:update_product' product.id %}">Edit</a>
    </span>
    <span class="w-1/5 mx-10 my-10">
        <a class="bg-red-500 text-white font-bold px-5 py-2" href="{% url 'myapp:delete_product' product.id %}">Delete</a>
    </span>
</div>
{% endfor %}
{% endblock %}

myapp/templates/myapp/product_confirm_delete.html
<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{object }}"</p>
  {{form}}
  <input type="submit" value="confirm" />
</form>

myapp/templates/myapp/product_form.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">+ Add products</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype = 'multipart/form-data'>
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <div class="shadow w-1/4 appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
        >{{form.name}}</div>
        
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product price</label>
        <div class="shadow w-1/4 appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
        >{{form.price}}</div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product description</label>
        <div class="shadow w-1/4 appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
        >{{form.desc}}</div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product image</label>
        <div class="shadow w-1/4 appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
        >{{form.image}}</div> 
        <div class="mb-4">
            <div class=" hidden shadow w-1/4 appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
            >{{form.seller_name}}</div>  
        </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Add product"> 
    </div>
    
</form>

{% endblock %}

myapp/templates/myapp/product_update_form.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" name="Update" id="Update" />
</form>

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">+ Update products</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype = 'multipart/form-data'>
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="iPhone" type="text" value="{{product.name}}" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="900" value="{{product.price}}" type="text" name="price" id="price">
        
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="This is an iPhone" value="{{product.desc}}" type="text" name="desc" id="desc">
        
    </div>
    <div class="mb-4">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product image</label>
        <input class="py-2 mr-10 text-gray-700" placeholder="Browse..." type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Update product" value="Update product"> 
    </div>
    
</form>

{% endblock %}

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-4">
            <label >Upload profile image</label>
            <input class="py-2" placeholder="Upload a clear profile pic" type="file" accept="image/*" name="upload" id="upload">
        </div>
        <div class="mb-4">
            <label >Contact</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="999999999" type="text" name="contact_number" id="contact_number">
        </div>
        <input class="bg-green-500 text-white px-5 py-2" name="Add" value="Add" type="submit">
    </form>
{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">Login User</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight" >{{ form.username }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight" >{{ form.password }}</div>
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Login</button>
    </form>
    <div class="m-10">Already have an account?<a class="text-indigo-500 font-bold" href="{% url 'users:register' %}">Register</a></div>
</div>

{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">Logout</h1>
<div class="container py-5">
    <h1 class="text-2xl m-10">You have been logged out</h1>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            {{user.username}}
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            {{user.profile.contact_number}}
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">Register User</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight" >{{ form.username }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight" >{{ form.email }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight" >{{ form.password1 }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight" >{{ form.password2 }}</div>
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
    </form>
    <div class="m-10">Do not have an account?<a class="text-indigo-500 font-bold" href="{% url 'users:login' %}">Login instead</a></div>

</div>

{% endblock %}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{seller.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            {{seller.username}}
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            {{seller.profile.contact_number}}
        </div>
    </div>
</div>

{% endblock %}